
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(311, 289)
        Form.setMinimumSize(QtCore.QSize(311, 289))
        Form.setMaximumSize(QtCore.QSize(311, 289))
        Form.setSizeIncrement(QtCore.QSize(0, 289))
        self.pushButton_send = QtWidgets.QPushButton(Form)
        self.pushButton_send.setGeometry(QtCore.QRect(100, 190, 100, 32))
        self.pushButton_send.setObjectName("pushButton_send")
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(70, 100, 171, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(70, 160, 171, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(100, 27, 91, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.label_username = QtWidgets.QLabel(Form)
        self.label_username.setGeometry(QtCore.QRect(130, 101, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("color : rgb(175, 177, 177)")
        self.label_username.setScaledContents(False)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(130, 161, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color : rgb(175, 177, 177)")
        self.label_password.setObjectName("label_password")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(50, 140, 211, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_text = QtWidgets.QLabel(Form)
        self.label_text.setGeometry(QtCore.QRect(30, 240, 241, 16))
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.lineEdit_username.raise_()
        self.label_username.raise_()
        self.line.raise_()
        self.pushButton_send.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.label_text.raise_()
        self.lineEdit_password.raise_()
        self.label_password.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_send.setText(_translate("Form", "SEND"))
        self.label_2.setText(_translate("Form", "LOGIN"))
        self.label_username.setText(_translate("Form", "username"))
        self.label_password.setText(_translate("Form", "password"))


