# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(489, 424)
        self.label_product_name = QtWidgets.QLabel(Form)
        self.label_product_name.setGeometry(QtCore.QRect(30, 110, 91, 21))
        self.label_product_name.setObjectName("label_product_name")
        self.lineEdit_code = QtWidgets.QLineEdit(Form)
        self.lineEdit_code.setGeometry(QtCore.QRect(140, 110, 113, 21))
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.label_count = QtWidgets.QLabel(Form)
        self.label_count.setGeometry(QtCore.QRect(60, 240, 58, 16))
        self.label_count.setObjectName("label_count")
        self.spinBox_count = QtWidgets.QSpinBox(Form)
        self.spinBox_count.setGeometry(QtCore.QRect(120, 240, 42, 22))
        self.spinBox_count.setObjectName("spinBox_count")
        self.pushButton_remove = QtWidgets.QPushButton(Form)
        self.pushButton_remove.setGeometry(QtCore.QRect(60, 280, 100, 32))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 80, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_product_information = QtWidgets.QLabel(Form)
        self.label_product_information.setGeometry(QtCore.QRect(30, 150, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_product_information.setFont(font)
        self.label_product_information.setText("")
        self.label_product_information.setObjectName("label_product_information")
        self.label_message = QtWidgets.QLabel(Form)
        self.label_message.setGeometry(QtCore.QRect(30, 330, 301, 31))
        self.label_message.setText("")
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.label_warning_code = QtWidgets.QLabel(Form)
        self.label_warning_code.setGeometry(QtCore.QRect(260, 110, 171, 16))
        self.label_warning_code.setText("")
        self.label_warning_code.setObjectName("label_warning_code")
        self.label_invalid_count = QtWidgets.QLabel(Form)
        self.label_invalid_count.setGeometry(QtCore.QRect(180, 250, 201, 16))
        self.label_invalid_count.setText("")
        self.label_invalid_count.setObjectName("label_invalid_count")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_product_name.setText(_translate("Form", "Product Code:"))
        self.label_count.setText(_translate("Form", "Count:"))
        self.pushButton_remove.setText(_translate("Form", "REMOVE"))
        self.label.setText(_translate("Form", "Product Informations to remove:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
